### ISSUE TITLE
Documentation says 'report_path' instead of 'path'

### ISSUE THREAD

**Issue by ab-iman** [mgrijalva/nose2-html-report#3]
In nose2.cfg or unittest.cfg's `[html-report]` section, the key name to specify report path should be `path`. It is incorrectly documented as `report_path`. Using `report_path` has no effect, whereas `path` works as expected.

**Comment by mgrijalva** [comment]
Ah good catch. I'll push out a fix when I get a chance. Feel free to submit a pull request if you want. It's this line that's the problem:
https://github.com/mgrijalva/nose2-html-report/blob/master/nose2_html_report/html_report.py#L24

**Comment by ab-iman** [comment]
1. Would you prefer to change the documentation or change the code? 
2. Do we care about maintaining backwards compatibility?

**Comment by mgrijalva** [comment]
I'm just going to update the documentation. I wouldn't want to push out any surprise breaking changes on anyone.
