### ISSUE TITLE
Docstrings don't appear in HTML report

### ISSUE THREAD

**Issue by olenoble** [mgrijalva/nose2-html-report#7]
Hi

I can't seem to get the docstring to show in the html report. 
Please find below a dummy example. I can run the test (all passed obviously) but see this in the html report:

test_nose1.TestVariousStuff.test_1
Description

This test has no docstring...

Code Example:
class TestVariousStuff:

    def __init__(self):
        self.x = 3
        self.y = 2

    def test_1(self):
        """
        test_1 runs a basic sums

        :return: pass is sum of x and y adds up to 5
        """
        npt.assert_equal(self.x + self.y, 5)

    def test_2(self):
        """
        Basic check with ratio
        """
        npt.assert_equal(self.x / 3, 1)

**Comment by mgrijalva** [comment]
The code you posted doesn't seem to run for me. I end up with this exception:

```
    loaded_suite = event.loader.suiteClass(map(testCaseClass, names))
TypeError: __init__() takes exactly 1 argument (2 given)
```

It's better to use `setUp` for this:

```python
class TestVariousStuff(unittest.TestCase):
    def setUp(self):
        self.x = 3
        self.y = 2
```

If you need to use __init__ make sure you're preserving the parent class' behavior:
```python
    def __init__(self, *args, **kwargs):
        super(TestVariousStuff, self).__init__(*args, **kwargs)
        self.x = 3
        self.y = 2
```

**Comment by olenoble** [comment]
Thanks - I can see the docstrings now. It seems that all I needed was this:

class TestVariousStuff(unittest.TestCase):    
    def __init__(self, *args, **kwargs):
        super(TestVariousStuff, self).__init__(*args, **kwargs)

My class (TestVariousStuff) didn't inherit from a parent class (which is why my init didn't require any any argument). With the above, it's all good now.
